"""adds board and card model

Revision ID: 1606de931605
Revises: 
Create Date: 2023-01-03 10:42:04.111203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1606de931605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.alter_column('board', 'board_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board', 'owner',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('board', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('board', 'owner',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('board', 'board_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('card',
    sa.Column('card_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('card_id', name='card_pkey')
    )
    # ### end Alembic commands ###
