"""empty message

Revision ID: 271aaa7400d4
Revises: a72186b8c63c
Create Date: 2021-06-29 18:12:09.821703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271aaa7400d4'
down_revision = 'a72186b8c63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('board_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('board', 'id')
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    op.drop_column('card', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'card_id')
    op.drop_column('card', 'board_id')
    op.add_column('board', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('board', 'board_id')
    # ### end Alembic commands ###
