"""empty message

Revision ID: 456c575cd4a3
Revises: 0998518428e5
Create Date: 2021-07-13 11:00:17.480900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456c575cd4a3'
down_revision = '0998518428e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'card', ['card_id'], ['card_id'])
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'card_id')
    # ### end Alembic commands ###
