"""empty message

Revision ID: 698776f3fbcf
Revises: 5914cb95c7e9
Create Date: 2021-07-13 14:24:11.948379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698776f3fbcf'
down_revision = '5914cb95c7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
