"""connect Board and Card models

Revision ID: 946adbcdc187
Revises: dd65e198b725
Create Date: 2025-06-24 11:21:43.320828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946adbcdc187'
down_revision = 'dd65e198b725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['board_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('board_id')

    # ### end Alembic commands ###
